"""Generated stubs for `pycro`.

Do not edit this file manually.
The engine loads `main.py` and dispatches required `update(dt)` on each frame.
"""

from typing import TypeAlias

Color: TypeAlias = tuple[float, float, float, float]
"""Normalized RGBA tuple."""

Vec2: TypeAlias = tuple[float, float]
"""Two-dimensional vector tuple."""

TextureHandle: TypeAlias = str
"""Opaque texture handle returned by the engine."""

__all__ = ["Color", "Vec2", "TextureHandle", "clear_background", "draw_circle", "is_key_down", "frame_time", "load_texture", "draw_texture", "set_camera_target", "draw_text", "submit_render", "submit_circle_batch"]

def clear_background(color: Color) -> None:
    """Clear the current frame to a normalized RGBA color. Supported on desktop=planned, web=planned, android=planned, ios=planned."""
    ...

def draw_circle(position: Vec2, radius: float, color: Color) -> None:
    """Draw a filled circle using world-space coordinates. Supported on desktop=planned, web=planned, android=planned, ios=planned."""
    ...

def is_key_down(key: str) -> bool:
    """Return whether a named key is held on the current frame. Supported on desktop=planned, web=planned, android=planned, ios=planned."""
    ...

def frame_time() -> float:
    """Return the last frame delta time in seconds. Supported on desktop=planned, web=planned, android=planned, ios=planned."""
    ...

def load_texture(path: str) -> TextureHandle:
    """Load a texture asset and return an opaque handle. Supported on desktop=planned, web=planned, android=planned, ios=planned."""
    ...

def draw_texture(texture: TextureHandle, position: Vec2, size: Vec2) -> None:
    """Draw a texture at a world-space position and size. Supported on desktop=planned, web=planned, android=planned, ios=planned."""
    ...

def set_camera_target(target: Vec2) -> None:
    """Move the active camera target to the provided world position. Supported on desktop=planned, web=planned, android=planned, ios=planned."""
    ...

def draw_text(text: str, position: Vec2, font_size: float, color: Color) -> None:
    """Draw text in screen space using a baseline anchor. Supported on desktop=planned, web=planned, android=planned, ios=planned."""
    ...

def submit_render(commands: list[tuple[object, ...]]) -> None:
    """Queue multiple render commands in one Python-to-runtime call. Supported on desktop=planned, web=planned, android=planned, ios=planned."""
    ...

def submit_circle_batch(positions: list[Vec2], radii: list[float], colors: list[Color]) -> None:
    """Queue many draw_circle operations in one specialized batch call. Supported on desktop=planned, web=planned, android=planned, ios=planned."""
    ...

