"""Generated stubs for `pycro`.

Do not edit this file manually.
The engine loads `main.py` and dispatches required `update(dt)` on each frame.
"""

from enum import Enum
from typing import TypeAlias

Color: TypeAlias = tuple[float, float, float, float]
"""Normalized RGBA tuple."""

Vec2: TypeAlias = tuple[float, float]
"""Two-dimensional vector tuple."""

TextureHandle: TypeAlias = str
"""Opaque texture handle returned by the engine."""

class KEY(str, Enum):
    """Supported input keys for `is_key_down`."""
    SPACE = "Space"
    APOSTROPHE = "Apostrophe"
    COMMA = "Comma"
    MINUS = "Minus"
    PERIOD = "Period"
    SLASH = "Slash"
    KEY_0 = "Key0"
    KEY_1 = "Key1"
    KEY_2 = "Key2"
    KEY_3 = "Key3"
    KEY_4 = "Key4"
    KEY_5 = "Key5"
    KEY_6 = "Key6"
    KEY_7 = "Key7"
    KEY_8 = "Key8"
    KEY_9 = "Key9"
    SEMICOLON = "Semicolon"
    EQUAL = "Equal"
    A = "A"
    B = "B"
    C = "C"
    D = "D"
    E = "E"
    F = "F"
    G = "G"
    H = "H"
    I = "I"
    J = "J"
    K = "K"
    L = "L"
    M = "M"
    N = "N"
    O = "O"
    P = "P"
    Q = "Q"
    R = "R"
    S = "S"
    T = "T"
    U = "U"
    V = "V"
    W = "W"
    X = "X"
    Y = "Y"
    Z = "Z"
    LEFT_BRACKET = "LeftBracket"
    BACKSLASH = "Backslash"
    RIGHT_BRACKET = "RightBracket"
    GRAVE_ACCENT = "GraveAccent"
    WORLD_1 = "World1"
    WORLD_2 = "World2"
    ESCAPE = "Escape"
    ENTER = "Enter"
    TAB = "Tab"
    BACKSPACE = "Backspace"
    INSERT = "Insert"
    DELETE = "Delete"
    RIGHT = "Right"
    LEFT = "Left"
    DOWN = "Down"
    UP = "Up"
    PAGE_UP = "PageUp"
    PAGE_DOWN = "PageDown"
    HOME = "Home"
    END = "End"
    CAPS_LOCK = "CapsLock"
    SCROLL_LOCK = "ScrollLock"
    NUM_LOCK = "NumLock"
    PRINT_SCREEN = "PrintScreen"
    PAUSE = "Pause"
    F1 = "F1"
    F2 = "F2"
    F3 = "F3"
    F4 = "F4"
    F5 = "F5"
    F6 = "F6"
    F7 = "F7"
    F8 = "F8"
    F9 = "F9"
    F10 = "F10"
    F11 = "F11"
    F12 = "F12"
    F13 = "F13"
    F14 = "F14"
    F15 = "F15"
    F16 = "F16"
    F17 = "F17"
    F18 = "F18"
    F19 = "F19"
    F20 = "F20"
    F21 = "F21"
    F22 = "F22"
    F23 = "F23"
    F24 = "F24"
    F25 = "F25"
    KP_0 = "Kp0"
    KP_1 = "Kp1"
    KP_2 = "Kp2"
    KP_3 = "Kp3"
    KP_4 = "Kp4"
    KP_5 = "Kp5"
    KP_6 = "Kp6"
    KP_7 = "Kp7"
    KP_8 = "Kp8"
    KP_9 = "Kp9"
    KP_DECIMAL = "KpDecimal"
    KP_DIVIDE = "KpDivide"
    KP_MULTIPLY = "KpMultiply"
    KP_SUBTRACT = "KpSubtract"
    KP_ADD = "KpAdd"
    KP_ENTER = "KpEnter"
    KP_EQUAL = "KpEqual"
    LEFT_SHIFT = "LeftShift"
    LEFT_CONTROL = "LeftControl"
    LEFT_ALT = "LeftAlt"
    LEFT_SUPER = "LeftSuper"
    RIGHT_SHIFT = "RightShift"
    RIGHT_CONTROL = "RightControl"
    RIGHT_ALT = "RightAlt"
    RIGHT_SUPER = "RightSuper"
    MENU = "Menu"
    BACK = "Back"
    MOUSE_LEFT = "MOUSE_LEFT"
    MOUSE_RIGHT = "MOUSE_RIGHT"
    MOUSE_MIDDLE = "MOUSE_MIDDLE"

__all__ = ["Color", "Vec2", "TextureHandle", "KEY", "clear_background", "draw_circle", "is_key_down", "frame_time", "load_texture", "draw_texture", "set_camera_target", "draw_text", "get_window_size", "get_mouse_position", "draw_rectangle", "put_pixel", "draw_line", "submit_render", "submit_circle_batch"]

def clear_background(color: Color) -> None:
    """Clear the current frame to a normalized RGBA color. Supported on desktop=planned, web=planned, android=planned, ios=planned."""
    ...

def draw_circle(position: Vec2, radius: float, color: Color) -> None:
    """Draw a filled circle using world-space coordinates. Supported on desktop=planned, web=planned, android=planned, ios=planned."""
    ...

def is_key_down(key: KEY) -> bool:
    """Return whether a named key is held on the current frame. Supported on desktop=planned, web=planned, android=planned, ios=planned."""
    ...

def frame_time() -> float:
    """Return the last frame delta time in seconds. Supported on desktop=planned, web=planned, android=planned, ios=planned."""
    ...

def load_texture(path: str) -> TextureHandle:
    """Load a texture asset and return an opaque handle. Supported on desktop=planned, web=planned, android=planned, ios=planned."""
    ...

def draw_texture(texture: TextureHandle, position: Vec2, size: Vec2) -> None:
    """Draw a texture at a world-space position and size. Supported on desktop=planned, web=planned, android=planned, ios=planned."""
    ...

def set_camera_target(target: Vec2) -> None:
    """Move the active camera target to the provided world position. Supported on desktop=planned, web=planned, android=planned, ios=planned."""
    ...

def draw_text(text: str, position: Vec2, font_size: float, color: Color) -> None:
    """Draw text in screen space using a baseline anchor. Supported on desktop=planned, web=planned, android=planned, ios=planned."""
    ...

def get_window_size() -> Vec2:
    """Return the current window width and height in pixels. Supported on desktop=planned, web=planned, android=planned, ios=planned."""
    ...

def get_mouse_position() -> Vec2:
    """Return the current mouse x/y coordinates in screen space. Supported on desktop=planned, web=planned, android=planned, ios=planned."""
    ...

def draw_rectangle(x: float, y: float, width: float, height: float, color: Color) -> None:
    """Draw a filled rectangle in screen space. Supported on desktop=planned, web=planned, android=planned, ios=planned."""
    ...

def put_pixel(x: float, y: float, color: Color) -> None:
    """Draw a single pixel at the given screen-space position. Supported on desktop=planned, web=planned, android=planned, ios=planned."""
    ...

def draw_line(x1: float, y1: float, x2: float, y2: float, color: Color) -> None:
    """Draw a 1px line segment in screen space. Supported on desktop=planned, web=planned, android=planned, ios=planned."""
    ...

def submit_render(commands: list[tuple[object, ...]]) -> None:
    """Queue multiple render commands in one Python-to-runtime call. Supported on desktop=planned, web=planned, android=planned, ios=planned."""
    ...

def submit_circle_batch(positions: list[Vec2], radii: list[float], colors: list[Color]) -> None:
    """Queue many draw_circle operations in one specialized batch call. Supported on desktop=planned, web=planned, android=planned, ios=planned."""
    ...

